In [1]:
import numpy as np
import pandas as pd

In [16]:
output_data=np.loadtxt(f"FD_Curve.txt", skiprows=2)


#print(output_data)
#column 1 is time
#column 2 is disp
#column 3 is force

# Remove X column from output_data
output_data = np.delete(output_data, 0, 1)
forceinkN = output_data[:, 1] * 1e-3 

# Insert into output_data as 2nd column and push Force/N to 3rd column
output_data = np.insert(output_data, 1, forceinkN, axis=1)

print(output_data)
columns=['Disp/mm', 'Force/kN', 'Force/N']
df = pd.DataFrame(data=output_data, columns=columns)
# Save dataframe
df.to_csv('FD_Curve.csv', index=False)


displacement = df.iloc[:, 0].tolist()
print(displacement)
force = df.iloc[:, 1].tolist()
print(force)

[[0.00000e+00 3.12565e-03 3.12565e+00]
 [3.00013e-02 1.07772e+00 1.07772e+03]
 [6.00055e-02 2.17217e+00 2.17217e+03]
 [8.99964e-02 3.31913e+00 3.31913e+03]
 [1.20005e-01 4.25807e+00 4.25807e+03]
 [1.50013e-01 5.45100e+00 5.45100e+03]
 [1.79965e-01 6.02650e+00 6.02650e+03]
 [2.09917e-01 6.34481e+00 6.34481e+03]
 [2.39870e-01 6.59948e+00 6.59948e+03]
 [2.69856e-01 6.83585e+00 6.83585e+03]
 [2.99860e-01 7.02623e+00 7.02623e+03]
 [3.29793e-01 7.22769e+00 7.22769e+03]
 [3.59689e-01 7.42803e+00 7.42803e+03]
 [3.89590e-01 7.60762e+00 7.60762e+03]
 [4.19491e-01 7.76148e+00 7.76148e+03]
 [4.49393e-01 7.86365e+00 7.86365e+03]
 [4.79294e-01 7.96209e+00 7.96209e+03]
 [5.09195e-01 8.04128e+00 8.04128e+03]
 [5.39096e-01 8.12303e+00 8.12303e+03]
 [5.68997e-01 8.18368e+00 8.18368e+03]
 [5.99011e-01 8.24762e+00 8.24762e+03]
 [6.29151e-01 8.30244e+00 8.30244e+03]
 [6.59296e-01 8.34986e+00 8.34986e+03]
 [6.89436e-01 8.39545e+00 8.39545e+03]
 [7.19576e-01 8.43642e+00 8.43642e+03]
 [7.49721e-01 8.47404e+00

In [8]:
def replace_maxDisp_geometry_inp(filePath, maxDisp):
    with open(filePath, 'r') as geometry_inp:
        geometry_inp_content = geometry_inp.readlines()
    start_line = None
    end_line = None
    for i, line in enumerate(geometry_inp_content[-60:]):
        if line.startswith('*Boundary, amplitude'):
            original_index = len(geometry_inp_content) - 60 + i
            start_line = original_index + 1
            end_line = original_index + 2
            break

    if start_line is None or end_line is None:
        raise ValueError('Could not find the *Boundary, amplitude displacement section')

    new_disp_data = f"Disp, 2, 2, {maxDisp}\n"

    new_lines = []
    new_lines.extend(geometry_inp_content[:start_line])
    new_lines.extend([new_disp_data])
    new_lines.extend(geometry_inp_content[end_line:])

    with open('geometry2.inp', 'w') as file:
        file.writelines(new_lines)

replace_maxDisp_geometry_inp('geometry.inp', 5.0)

59252
59253
59254


In [10]:
def replace_materialName_geometry_inp(filePath):
    with open(filePath, 'r') as geometry_inp:
        geometry_inp_content = geometry_inp.readlines()
    start_line = None
    end_line = None
    for i, line in enumerate(geometry_inp_content[-60:]):
        if line.startswith('*INCLUDE, INPUT='):
            original_index = len(geometry_inp_content) - 60 + i
            start_line = original_index
            end_line = original_index + 1
            break

    if start_line is None or end_line is None:
        raise ValueError('Could not find the **INCLUDE, INPUT= section')

    new_material_data = f"*INCLUDE, INPUT=material.inp\n"

    new_lines = []
    new_lines.extend(geometry_inp_content[:start_line])
    new_lines.extend([new_material_data])
    new_lines.extend(geometry_inp_content[end_line:])

    with open('geometry3.inp', 'w') as file:
        file.writelines(new_lines)

replace_materialName_geometry_inp('geometry.inp')