In [2]:
import numpy as np
import pandas as pd

In [4]:
output_data=np.loadtxt(f"FD_Curve.txt", skiprows=2)


#print(output_data)
#column 1 is time
#column 2 is disp
#column 3 is force

# Remove X column from output_data
output_data = np.delete(output_data, 0, 1)
forceinkN = output_data[:, 1] * 1e-3 

# Insert into output_data as 2nd column and push Force/N to 3rd column
output_data = np.insert(output_data, 1, forceinkN, axis=1)

print(output_data)
columns=['Disp/mm', 'Force/kN', 'Force/N']
df = pd.DataFrame(data=output_data, columns=columns)
# Save dataframe
df.to_csv('FD_Curve.csv', index=False)


displacement = df.iloc[:, 0].tolist()
print(displacement)
force = df.iloc[:, 1].tolist()
print(force)

[[0.00000e+00 3.12565e-03 3.12565e+00]
 [3.00013e-02 1.07772e+00 1.07772e+03]
 [6.00055e-02 2.17217e+00 2.17217e+03]
 [8.99964e-02 3.31913e+00 3.31913e+03]
 [1.20005e-01 4.25807e+00 4.25807e+03]
 [1.50013e-01 5.45308e+00 5.45308e+03]
 [1.79965e-01 6.45376e+00 6.45376e+03]
 [2.09917e-01 7.14830e+00 7.14830e+03]
 [2.39870e-01 7.43786e+00 7.43786e+03]
 [2.69857e-01 7.65692e+00 7.65692e+03]
 [2.99860e-01 7.87758e+00 7.87758e+03]
 [3.29864e-01 8.00768e+00 8.00768e+03]
 [3.59822e-01 8.13443e+00 8.13443e+03]
 [3.89723e-01 8.24041e+00 8.24041e+03]
 [4.19624e-01 8.33398e+00 8.33398e+03]
 [4.49525e-01 8.40454e+00 8.40454e+03]
 [4.79426e-01 8.48106e+00 8.48106e+03]
 [5.09327e-01 8.54137e+00 8.54137e+03]
 [5.39228e-01 8.59793e+00 8.59793e+03]
 [5.69129e-01 8.64430e+00 8.64430e+03]
 [5.99144e-01 8.68916e+00 8.68916e+03]
 [6.29284e-01 8.72863e+00 8.72863e+03]
 [6.59429e-01 8.76417e+00 8.76417e+03]
 [6.89569e-01 8.79398e+00 8.79398e+03]
 [7.19709e-01 8.81901e+00 8.81901e+03]
 [7.49854e-01 8.84020e+00

In [8]:
def replace_maxDisp_geometry_inp(filePath, maxDisp):
    with open(filePath, 'r') as geometry_inp:
        geometry_inp_content = geometry_inp.readlines()
    start_line = None
    end_line = None
    for i, line in enumerate(geometry_inp_content[-60:]):
        if line.startswith('*Boundary, amplitude'):
            original_index = len(geometry_inp_content) - 60 + i
            start_line = original_index + 1
            end_line = original_index + 2
            break

    if start_line is None or end_line is None:
        raise ValueError('Could not find the *Boundary, amplitude displacement section')

    new_disp_data = f"Disp, 2, 2, {maxDisp}\n"

    new_lines = []
    new_lines.extend(geometry_inp_content[:start_line])
    new_lines.extend([new_disp_data])
    new_lines.extend(geometry_inp_content[end_line:])

    with open('geometry2.inp', 'w') as file:
        file.writelines(new_lines)

replace_maxDisp_geometry_inp('geometry.inp', 5.0)

59252
59253
59254


In [10]:
def replace_materialName_geometry_inp(filePath):
    with open(filePath, 'r') as geometry_inp:
        geometry_inp_content = geometry_inp.readlines()
    start_line = None
    end_line = None
    for i, line in enumerate(geometry_inp_content[-60:]):
        if line.startswith('*INCLUDE, INPUT='):
            original_index = len(geometry_inp_content) - 60 + i
            start_line = original_index
            end_line = original_index + 1
            break

    if start_line is None or end_line is None:
        raise ValueError('Could not find the **INCLUDE, INPUT= section')

    new_material_data = f"*INCLUDE, INPUT=material.inp\n"

    new_lines = []
    new_lines.extend(geometry_inp_content[:start_line])
    new_lines.extend([new_material_data])
    new_lines.extend(geometry_inp_content[end_line:])

    with open('geometry3.inp', 'w') as file:
        file.writelines(new_lines)

replace_materialName_geometry_inp('geometry.inp')